---
- include: debian.yml
  when:
    ansible_os_family == "Debian"

- include: rhel.yml
  when:
    ansible_os_family == "RedHat"

- name: Install Squid configuration
  template:
    src: squid.conf.j2
    dest: /etc/squid/squid.conf
    owner: root
    group: root
    mode: 0640
  notify:
    restart squid

- name: Enable/Start Squid service
  service:
    name: squid
    state: started
    enabled: yes
